name: my_app1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.1.0
  shared_preferences: ^2.2.2
  get_storage: ^2.1.0 
  lottie: ^2.7.0
  image_picker: ^1.1.2
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/home logo2.png

# إعدادات flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/home logo2.png"
